modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)"
license="${mod_license}"
issueTrackerURL="https://github.com/illucc/Kontraption/issues"

[[mods]]
modId="kontraption"
version="${mod_version}"
displayName="${mod_name}" #mandatory
displayURL="https://github.com/illucc/Kontraption" #optional
logoFile="kontraption.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies.kontraption]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies.kontraption]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.kontraption]]
   modId="mekanism"
   mandatory=true
   versionRange="[10,)"
   ordering="BEFORE"
   side="BOTH"
[[dependencies.kontraption]]
   modId="kotlinforforge"
   mandatory=true
   versionRange="[3,)"
   ordering="BEFORE"
   side="BOTH"


